import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Courgette } from "next/font/google";
import "../../globals.css";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import { Lang } from "@/common/types";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const courgette = Courgette({
  weight: "400",
  variable: "--font-courgette",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  themeColor: '#fff'
}

// export const LangContext = createContext({lang: 'tr'})

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: ReactNode,
  params: Promise<{ lang: Lang }>
}>) {
  const { lang } = await params

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${courgette.variable} antialiased`}
      >
        <Header lang={lang} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
